on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
env:
  SIMPLE_SECRET: ${{ secrets.SIMPLE_SECRET }}
  SIMPLE_VAR: ${{ vars.SIMPLE_VAR }}

jobs:
  log-the-inputs:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Simple Secret: $SIMPLE_SECRET"
          echo "Simple Var: $SIMPLE_VAR"
