on:
  workflow_dispatch:
env:
  PROVIDER_VARS: ${{ secrets.PROVIDER_VARS }}

jobs:
  log-the-inputs:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          for s in $(echo $PROVIDER_VARS | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" ); do
            export $s
          done
          

